version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./application/adapter/src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
